packages:
  - "fixtures/*"
catalogs:
  dev:
    "@antfu/ni": ^25.0.0
    "@eslint/config-inspector": ^1.0.2
    "@types/node": ^22.15.12
    bumpp: ^10.1.1
    eslint-typegen: ^2.2.0
    execa: ^9.5.3
    husky: ^9.1.7
    jiti: ^2.4.2
    lint-staged: ^16.0.0
    pnpm-workspace-yaml: ^0.3.1
    tinyglobby: ^0.2.13
    tsup: ^8.5.0
    tsx: ^4.19.4
    typescript: ^5.8.3
    vitest: ^3.1.4
  peer:
    "@eslint-react/eslint-plugin": ^1.49.0
    "@prettier/plugin-xml": ^3.4.1
    "@unocss/eslint-plugin": ^66.1.2
    astro-eslint-parser: ^1.2.2
    eslint: ^9.27.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-vuejs-accessibility: ^2.4.1
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    vue: ^3.5.14
  prod:
    "@antfu/install-pkg": ^1.1.0
    "@clack/prompts": ^0.10.1
    "@eslint-community/eslint-plugin-eslint-comments": ^4.5.0
    "@eslint/markdown": ^6.4.0
    "@stylistic/eslint-plugin": ^4.2.0
    "@typescript-eslint/eslint-plugin": ^8.32.1
    "@typescript-eslint/parser": ^8.32.1
    "@vitest/eslint-plugin": ^1.2.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.2.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^51.3.2
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.18.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.13.0
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-regexp: ^2.7.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.1.0
    eslint-plugin-yml: ^1.18.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.1.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    parse-gitignore: ^2.0.0
    prettier: ^3.5.3
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.1.3
    yaml-eslint-parser: ^1.3.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
