[
  "<ignored>",
  "<ignored>",
  "<ignored>",
  {
    "name": "xwbx/javascript/rules",
    "plugins": [
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "array-callback-return",
      "block-scoped-var",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-async-promise-executor",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-console",
      "no-const-assign",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-implied-eval",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-invalid-this",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-obj-calls",
      "no-octal",
      "no-octal-escape",
      "no-proto",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unused-expressions",
      "no-unused-vars",
      "no-use-before-define",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "one-var",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "symbol-description",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "use-isnan",
      "valid-typeof",
      "vars-on-top",
      "yoda",
      "antfu/top-level-function",
    ],
  },
  {
    "name": "xwbx/eslint-comments/rules",
    "plugins": [
      "eslint-comments",
    ],
    "rules": [
      "eslint-comments/no-aggregating-enable",
      "eslint-comments/no-duplicate-disable",
      "eslint-comments/no-unlimited-disable",
      "eslint-comments/no-unused-enable",
    ],
  },
  {
    "name": "xwbx/command/rules",
    "plugins": [
      "command",
    ],
    "rules": [
      "command/command",
    ],
  },
  {
    "name": "xwbx/sort/import",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-imports",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
    ],
  },
  {
    "name": "xwbx/node/setup",
    "plugins": [
      "node",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/node/rules",
    "rules": [
      "node/handle-callback-err",
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-new-require",
      "node/no-path-concat",
      "node/no-unsupported-features/es-builtins",
      "node/prefer-global/buffer",
      "node/prefer-global/process",
      "node/process-exit-as-throw",
    ],
  },
  {
    "name": "xwbx/jsdoc/setup",
    "plugins": [
      "jsdoc",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/jsdoc/rules",
    "rules": [
      "jsdoc/check-access",
      "jsdoc/check-param-names",
      "jsdoc/check-property-names",
      "jsdoc/check-types",
      "jsdoc/empty-tags",
      "jsdoc/implements-on-classes",
      "jsdoc/no-defaults",
      "jsdoc/no-multi-asterisks",
      "jsdoc/require-param-name",
      "jsdoc/require-property",
      "jsdoc/require-property-description",
      "jsdoc/require-property-name",
      "jsdoc/require-returns-check",
      "jsdoc/require-returns-description",
      "jsdoc/require-yields-check",
    ],
  },
  {
    "name": "xwbx/formatter/setup",
    "plugins": [
      "format",
      "style",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "ignores": [
      "**/*.astro/**",
    ],
    "name": "xwbx/formatter/jslike",
    "rules": [
      "style/quotes",
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.vue",
    ],
    "ignores": [
      "**/*.astro/**",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/vue",
    "rules": [
      "style/quotes",
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.json",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/json",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.jsonc",
    ],
    "name": "xwbx/formatter/jsonc",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.json5",
    ],
    "name": "xwbx/formatter/json5",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "name": "xwbx/formatter/toml",
    "rules": [
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "files": [
      "**/*.css",
      "**/*.{p,post}css",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/css",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.scss",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/scss",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.less",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/less",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.htm?(l)",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/html",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.xml",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/xml",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.svg",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/svg",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "ignores": [],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/markdown",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.astro",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/astro",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.astro",
      "**/*.astro/*.ts",
    ],
    "name": "xwbx/formatter/astro/disables",
    "rules": [
      "- style/arrow-parens",
      "- style/block-spacing",
      "- style/comma-dangle",
      "- style/indent",
      "- style/no-multi-spaces",
      "- style/quotes",
      "- style/semi",
    ],
  },
  {
    "files": [
      "**/*.{g,graph}ql",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "xwbx/formatter/graphql",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "name": "xwbx/formatter/yaml",
    "rules": [
      "format/prettier",
    ],
  },
  {
    "name": "xwbx/imports/rules",
    "plugins": [
      "antfu",
      "import",
    ],
    "rules": [
      "antfu/import-dedupe",
      "antfu/no-import-dist",
      "antfu/no-import-node-modules-by-path",
      "import/consistent-type-specifier-style",
      "import/first",
      "import/no-duplicates",
      "import/no-mutable-exports",
      "import/no-named-default",
      "- import/order",
      "import/newline-after-import",
    ],
  },
  {
    "name": "xwbx/unicorn",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "unicorn/catch-error-name",
      "unicorn/consistent-empty-array-spread",
      "unicorn/custom-error-definition",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/explicit-length-check",
      "unicorn/new-for-builtins",
      "unicorn/no-array-for-each",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-array-push-push",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-console-spaces",
      "unicorn/no-for-loop",
      "unicorn/no-hex-escape",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-lonely-if",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-unnecessary-await",
      "unicorn/no-zero-fractions",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat-map",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-date-now",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-dataset",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-includes",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-prototype-methods",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-reflect-apply",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-string-raw",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-string-trim-start-end",
      "unicorn/prefer-type-error",
      "unicorn/throw-new-error",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "xwbx/jsx/setup",
    "plugins": [],
    "rules": [],
  },
  {
    "name": "xwbx/typescript/setup",
    "plugins": [
      "antfu",
      "ts",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "extraFileExtensions": [],
        "sourceType": "module",
      },
    },
    "name": "xwbx/typescript/parser",
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "xwbx/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "ts/ban-ts-comment",
      "- no-array-constructor",
      "ts/no-array-constructor",
      "ts/no-duplicate-enum-values",
      "- ts/no-dynamic-delete",
      "ts/no-empty-object-type",
      "- ts/no-explicit-any",
      "ts/no-extra-non-null-assertion",
      "- ts/no-extraneous-class",
      "- ts/no-invalid-void-type",
      "ts/no-misused-new",
      "ts/no-namespace",
      "ts/no-non-null-asserted-nullish-coalescing",
      "ts/no-non-null-asserted-optional-chain",
      "- ts/no-non-null-assertion",
      "ts/no-require-imports",
      "ts/no-this-alias",
      "ts/no-unnecessary-type-constraint",
      "ts/no-unsafe-declaration-merging",
      "ts/no-unsafe-function-type",
      "- no-unused-expressions",
      "ts/no-unused-expressions",
      "- no-unused-vars",
      "- ts/no-unused-vars",
      "- no-useless-constructor",
      "- ts/no-useless-constructor",
      "ts/no-wrapper-object-types",
      "ts/prefer-as-const",
      "ts/prefer-literal-enum-member",
      "ts/prefer-namespace-keyword",
      "- ts/triple-slash-reference",
      "- ts/unified-signatures",
      "- no-use-before-define",
      "ts/consistent-type-definitions",
      "ts/consistent-type-imports",
      "ts/method-signature-style",
      "ts/no-dupe-class-members",
      "ts/no-import-type-side-effects",
      "ts/no-redeclare",
      "ts/no-use-before-define",
    ],
  },
  {
    "name": "xwbx/regexp/rules",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "- no-empty-character-class",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "files": [
      "**/__tests__/**/*.?([cm])[jt]s?(x)",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/*.bench.?([cm])[jt]s?(x)",
      "**/*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/test",
    "plugins": [
      "test",
    ],
    "rules": [
      "test/consistent-test-it",
      "test/no-identical-title",
      "test/no-import-node-test",
      "test/no-only-tests",
      "test/prefer-hooks-in-order",
      "test/prefer-lowercase-title",
      "- unicorn/consistent-function-scoping",
      "- antfu/no-top-level-await",
      "- no-unused-expressions",
      "- node/prefer-global/process",
      "- ts/explicit-function-return-type",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "language": "jsonc/x",
    "name": "xwbx/jsonc",
    "plugins": [
      "jsonc",
    ],
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-floating-decimal",
      "jsonc/no-hexadecimal-numeric-literals",
      "jsonc/no-infinity",
      "jsonc/no-multi-str",
      "jsonc/no-nan",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-octal",
      "jsonc/no-octal-escape",
      "jsonc/no-octal-numeric-literals",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "xwbx/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/[jt]sconfig.json",
      "**/[jt]sconfig.*.json",
    ],
    "name": "xwbx/sort/tsconfig-json",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "package.json",
      "**/package.json",
    ],
    "language": "jsonc/x",
    "name": "xwbx/pnpm/package-json",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/json-enforce-catalog",
      "pnpm/json-prefer-workspace-settings",
      "pnpm/json-valid-catalog",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "xwbx/pnpm/pnpm-workspace-yaml",
    "plugins": [
      "pnpm",
    ],
    "rules": [
      "pnpm/yaml-enforce-settings",
      "pnpm/yaml-no-duplicate-catalog-item",
      "pnpm/yaml-no-unused-catalog-item",
    ],
  },
  {
    "files": [
      "pnpm-workspace.yaml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "xwbx/pnpm/pnpm-workspace-yaml-sort",
    "plugins": [
      "yaml",
    ],
    "rules": [
      "yaml/sort-keys",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "xwbx/yaml/rules",
    "plugins": [
      "yaml",
    ],
    "rules": [
      "- style/spaced-comment",
      "yaml/no-empty-key",
      "yaml/no-empty-sequence-entry",
      "yaml/no-irregular-whitespace",
      "yaml/plain-scalar",
      "yaml/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "xwbx/toml",
    "plugins": [
      "toml",
    ],
    "rules": [
      "- style/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
    ],
  },
  {
    "name": "xwbx/markdown/setup",
    "plugins": [
      "markdown",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "ignores": [
      "**/*.md/*.md",
    ],
    "name": "xwbx/markdown/processor",
    "processor": "merged-processor:@eslint/markdown/markdown+pass-through",
  },
  {
    "files": [
      "**/*.md",
    ],
    "language": "markdown/gfm",
    "name": "xwbx/markdown/parser",
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "xwbx/markdown/rules",
    "rules": [
      "markdown/fenced-code-language",
      "markdown/heading-increment",
      "markdown/no-duplicate-definitions",
      "markdown/no-empty-definitions",
      "markdown/no-empty-images",
      "markdown/no-empty-links",
      "markdown/no-invalid-label-refs",
      "markdown/no-missing-atx-heading-space",
      "- markdown/no-missing-label-refs",
      "markdown/no-missing-link-fragments",
      "markdown/no-multiple-h1",
      "markdown/no-reference-like-urls",
      "markdown/no-reversed-media-syntax",
      "markdown/no-space-in-emphasis",
      "markdown/no-unused-definitions",
      "markdown/require-alt-text",
      "markdown/table-column-count",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "xwbx/markdown/disables/markdown",
    "rules": [
      "- command/command",
      "- no-irregular-whitespace",
      "- perfectionist/sort-exports",
      "- perfectionist/sort-imports",
      "- regexp/no-legacy-features",
      "- regexp/no-missing-g-flag",
      "- regexp/no-useless-dollar-replacements",
      "- regexp/no-useless-flag",
      "- style/indent",
    ],
  },
  {
    "files": [
      "**/*.md/**/*.?([cm])[jt]s?(x)",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "impliedStrict": true,
        },
      },
    },
    "name": "xwbx/markdown/disables/code",
    "rules": [
      "- antfu/no-top-level-await",
      "- import/newline-after-import",
      "- no-alert",
      "- no-console",
      "- no-labels",
      "- no-lone-blocks",
      "- no-restricted-syntax",
      "- no-undef",
      "- no-unused-expressions",
      "- no-unused-labels",
      "- no-unused-vars",
      "- node/prefer-global/process",
      "- style/comma-dangle",
      "- style/eol-last",
      "- style/padding-line-between-statements",
      "- ts/consistent-type-imports",
      "- ts/explicit-function-return-type",
      "- ts/no-namespace",
      "- ts/no-redeclare",
      "- ts/no-require-imports",
      "- ts/no-unused-expressions",
      "- ts/no-unused-vars",
      "- ts/no-use-before-define",
      "- unicode-bom",
      "- unused-imports/no-unused-imports",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/disables/scripts",
    "rules": [
      "- no-console",
      "- ts/explicit-function-return-type",
      "- unicorn/consistent-function-scoping",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/disables/cli",
    "rules": [
      "- no-console",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/disables/bin",
    "rules": [
      "- antfu/no-import-dist",
      "- antfu/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "xwbx/disables/dts",
    "rules": [
      "- eslint-comments/no-unlimited-disable",
      "- import/no-duplicates",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "xwbx/disables/cjs",
    "rules": [
      "- ts/no-require-imports",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "xwbx/disables/config-files",
    "rules": [
      "- no-console",
    ],
  },
]